const fs = require('fs');
const lines = [
'export type GrowthStage = "seed" | "early_growth" | "mid_growth" | "scaling";',
'',
'export function deriveGrowthStage(subscribers) {',
'  if (subscribers < 1000) return "seed";',
'  if (subscribers < 10000) return "early_growth";',
'  if (subscribers < 100000) return "mid_growth";',
'  return "scaling";',
'}',
'',
'export type BottleneckCategory = "discoverability" | "retention" | "niche_positioning";',
'',
'export interface BottleneckInputs {',
'  subscribers: number;',
'  channel_age_months: number;',
'  ctr_percent: number;',
'  ctr_trend: "declining" | "flat" | "improving";',
'  avg_view_duration_percent: number;',
'  sub_view_ratio_percent: number;',
'  niche_defined: boolean;',
'  source_reliability: "api" | "screenshot" | "manual_verified" | "manual" | "inferred";',
'  data_age_days: number;',
'}',
'',
'export interface LayerScore {',
'  category: BottleneckCategory;',
'  severity: number;',
'  confidence: number;',
'  leverage: number;',
'  momentum_modifier: number;',
'  base_impact_score: number;',
'  stage_weight: number;',
'  final_impact_score: number;',
'  selected: boolean;',
'}',
'',
'export interface DirectiveStep {',
'  step_number: number;',
'  action: string;',
'  tool_or_location: string | null;',
'}',
'',
'export interface Directive {',
'  title: string;',
'  rationale: string;',
'  time_estimate_minutes: number;',
'  steps: DirectiveStep[];',
'  success_condition: string;',
'}',
'',
'export interface Evidence {',
'  signal: string;',
'  benchmark: string;',
'  cost: string;',
'  confidence: "HIGH" | "MEDIUM" | "LOW";',
'}',
'',
'export interface BottleneckResult {',
'  growth_stage: GrowthStage;',
'  layers: LayerScore[];',
'  selected_bottleneck: BottleneckCategory;',
'  selected_impact_score: number;',
'  runner_up: { category: BottleneckCategory; score: number } | null;',
'  tie_detected: boolean;',
'  override_triggered: boolean;',
'  override_type: "recurrence" | "data_void" | "crisis" | "milestone_proximity" | null;',
'  evidence: Evidence;',
'  directive: Directive;',
'}',
'',
'export type CommitmentResponse = "yes" | "no" | "modified";',
'export type CommitmentObstacle = "time" | "clarity" | "motivation" | null;',
'',
'export interface CoachingSessionRow {',
'  id?: string;',
'  user_id: string;',
'  source_id: number;',
'  growth_stage: GrowthStage;',
'  selected_bottleneck: BottleneckCategory;',
'  final_impact_score: number;',
'  directive_title: string;',
'  directive_steps: DirectiveStep[];',
'  success_condition: string;',
'  raw_scores: LayerScore[];',
'  commitment_response: CommitmentResponse | null;',
'  override_triggered: boolean;',
'  override_type: string | null;',
'  created_at?: string;',
'}'
];
fs.writeFileSync('src/types/bottleneck.ts', lines.join('\n'), 'utf8');
console.log('done');
