const fs = require('fs');
const lines = [
'import { NextRequest, NextResponse } from "next/server";',
'import { createClient } from "@supabase/supabase-js";',
'import { runBottleneckEngine } from "@/lib/bottleneck/scoreEngine";',
'import type { BottleneckInputs, CoachingSessionRow } from "@/types/bottleneck";',
'',
'function getSupabase(authHeader) {',
'  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;',
'  const anon = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;',
'  const token = (authHeader || "").replace("Bearer ", "") || anon;',
'  return createClient(url, anon, { global: { headers: { Authorization: "Bearer " + token } } });',
'}',
'',
'function deriveCtrTrend(stats) {',
'  const valid = stats.filter(s => s.ctr_percent !== null && s.ctr_percent > 0).sort((a, b) => b.recorded_date.localeCompare(a.recorded_date));',
'  if (valid.length < 2) return "flat";',
'  const delta = ((valid[0].ctr_percent - valid[1].ctr_percent) / valid[1].ctr_percent) * 100;',
'  if (delta <= -10) return "declining";',
'  if (delta >= 10) return "improving";',
'  return "flat";',
'}',
'',
'function deriveChannelAgeMonths(sourceCreatedAt) {',
'  const created = new Date(sourceCreatedAt);',
'  const now = new Date();',
'  return (now.getFullYear() - created.getFullYear()) * 12 + (now.getMonth() - created.getMonth());',
'}',
'',
'function deriveDataAgeDays(recordedDate) {',
'  const recorded = new Date(recordedDate);',
'  const now = new Date();',
'  return Math.floor((now.getTime() - recorded.getTime()) / (1000 * 60 * 60 * 24));',
'}',
'',
'export async function POST(req) {',
'  try {',
'    const authHeader = req.headers.get("authorization");',
'    const supabase = getSupabase(authHeader);',
'    const { data: { user }, error: authError } = await supabase.auth.getUser();',
'    if (authError || !user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });',
'    const body = await req.json();',
'    const { source_id } = body;',
'    if (!source_id) return NextResponse.json({ error: "source_id is required" }, { status: 400 });',
'    const { data: source, error: sourceError } = await supabase.from("sources").select("id, niche, created_at, user_id").eq("id", source_id).eq("user_id", user.id).single();',
'    if (sourceError || !source) return NextResponse.json({ error: "Source not found" }, { status: 404 });',
'    const { data: latestStat, error: statError } = await supabase.from("source_stats").select("subscribers, views, ctr_percent, watch_time_percent, recorded_date").eq("source_id", source_id).order("recorded_date", { ascending: false }).limit(1).single();',
'    if (statError || !latestStat) return NextResponse.json({ error: "No stats found for this source. Add at least one stats entry before coaching." }, { status: 422 });',
'    const { data: trendStats } = await supabase.from("source_stats").select("ctr_percent, recorded_date").eq("source_id", source_id).order("recorded_date", { ascending: false }).limit(2);',
'    const subscribers = latestStat.subscribers || 0;',
'    const views = latestStat.views || 0;',
'    const subViewRatio = views > 0 ? (subscribers / views) * 100 : 0;',
'    const inputs = {',
'      subscribers,',
'      channel_age_months: deriveChannelAgeMonths(source.created_at),',
'      ctr_percent: latestStat.ctr_percent || 0,',
'      ctr_trend: deriveCtrTrend(trendStats || []),',
'      avg_view_duration_percent: latestStat.watch_time_percent || 0,',
'      sub_view_ratio_percent: subViewRatio,',
'      niche_defined: !!(source.niche && source.niche.trim() !== ""),',
'      source_reliability: "manual",',
'      data_age_days: deriveDataAgeDays(latestStat.recorded_date),',
'    };',
'    const result = runBottleneckEngine(inputs);',
'    const sessionRow = {',
'      user_id: user.id,',
'      source_id: source_id,',
'      growth_stage: result.growth_stage,',
'      selected_bottleneck: result.selected_bottleneck,',
'      final_impact_score: result.selected_impact_score,',
'      directive_title: result.directive.title,',
'      directive_steps: result.directive.steps,',
'      success_condition: result.directive.success_condition,',
'      raw_scores: result.layers,',
'      commitment_response: null,',
'      override_triggered: result.override_triggered,',
'      override_type: result.override_type,',
'    };',
'    const { data: inserted, error: insertError } = await supabase.from("coaching_sessions").insert(sessionRow).select("id").single();',
'    if (insertError) console.error("coaching_sessions insert failed:", insertError.message);',
'    await supabase.from("sources").update({ last_bottleneck: result.selected_bottleneck }).eq("id", source_id).eq("user_id", user.id);',
'    return NextResponse.json({ success: true, session_id: inserted ? inserted.id : null, result });',
'  } catch (err) {',
'    const message = err instanceof Error ? err.message : "Unknown error";',
'    return NextResponse.json({ error: "Internal server error", details: message }, { status: 500 });',
'  }',
'}'
];
fs.writeFileSync('src/app/api/jarvis/coach/route.ts', lines.join('\n'), 'utf8');
console.log('done');
