export enum ConstraintType {
  IDENTITY_MISMATCH = 'IDENTITY_MISMATCH',

  AUDIENCE_MISMATCH = 'AUDIENCE_MISMATCH',

  EXPECTATION_MISMATCH = 'EXPECTATION_MISMATCH',

  ATTENTION_LEAK = 'ATTENTION_LEAK',

  TRUST_LEAK = 'TRUST_LEAK',

  VALUE_EXCHANGE_LEAK = 'VALUE_EXCHANGE_LEAK',

  DISTRIBUTION_LEAK = 'DISTRIBUTION_LEAK',

  EXPERIMENT_NEEDED = 'EXPERIMENT_NEEDED',

  UNKNOWN = 'UNKNOWN'
}